# Generated by Django 3.2 on 2023-07-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_create_models_recipe_ingredient_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепты', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт-Ингредиент', 'verbose_name_plural': 'Рецепт-Ингредиент'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Рецепт-Тег', 'verbose_name_plural': 'Рецепт-Тег'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
    ]
