# Generated by Django 3.2 on 2023-07-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_uniqueconstraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique recipe-ingredient',
        ),
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique recipe-tag',
        ),
    ]
